### ISSUE TITLE
lacking documentation

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#118]
lacking documentation for available functions.

**Comment by luizbills** [comment]
we should add type signature to all functions (in source file and/or in README or wiki) and then we could create a more detailed documentation.

```js
// append :: String -> String -> String (is this right?)
const append = post => pre =>
  `${pre}${post}`
```

I don't know much about type signatures but I can help (and learn in the process)

**Comment by joelnet** [comment]
Good idea, I agree. I was working on docs last night. It was time consuming. I don't think I'll be able to do it all at once. So I'll merge in a few docs and iterate as I create more.

**Comment by luizbills** [comment]
I know... documentation is very tedious. I prefer to create some examples only haha

**Comment by joelnet** [comment]
I added some docs here: https://github.com/joelnet/MojiScript/tree/story/documentation

I added some type definitions. Hopefully I didn't make too many mistakes.

I haven't merged it into master because it's very sparse. I figure it should be about 80% complete (at least) before merging it in.

If you want to tackle some off this list, you can branch off of. Let me know though so we don't duplicate our efforts.

**Comment by joelnet** [comment]
I was trying to do the same earlier. I would really like to use codesandbox for demos. Not possible at the moment. It looks like they are actively working on it though https://github.com/CompuIves/codesandbox-client/issues/127.
