### ISSUE TITLE
Mojiscript CLI

### ISSUE THREAD

**Issue by luizbills** [joelnet/MojiScript#120]
I guess a CLI for lint/validate the source code, create a starter project, ... will be very useful.

**Comment by joelnet** [comment]
I was considering that also. It would be fairly easy to do using existing tools like `eslint`. But the project still needs an `eslintrc.yml` file to validate in the editor (vscode for me).

It would be nice to move all the config out of the `eslintrc.yml` file into a custom ruleset like how `eslint-config-airbnb` works. I'm not sure how that works with plugins also. So maybe something more like how `eslint-plugin-fp` works.

There are still `eslint` rules that need to be added. Mostly to block synchronous JavaScript, like the rules to block `function`.

So I think getting the eslint rules in a stable place would be the first step.

**Comment by luizbills** [comment]
`eslint` has a `CLIEngine` object: https://eslint.org/docs/developer-guide/nodejs-api#cliengine

We can create a cli powered by this CLIEngine.

**Comment by joelnet** [comment]
Interesting. Seems like that'll be good for unit testing custom plugins. That could be used for the CLI. the CLI could also just execute a shell script for `eslint`.

It doesn't look like that would be useful for custom rules in the IDE though.

**Comment by joelnet** [comment]
Need an eslint rule to block `if` statements.

**Comment by luizbills** [comment]
I guess we should we must block .eslintrc files and lint only with our predefined rules inside of mojiscript cli. It does not make sense for me to let the user define their own eslint rules

**Comment by joelnet** [comment]
I think instead of blocking the eslint, we have a ruleset like:

```yaml
env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - mojiscript
extends: 'plugin:mojiscript/recommended'
```

I believe we still need to keep the `eslint` file for IDE's like VSCODE. I don't know how to get linting to work in the IDE without eslint. Not an easy way at least.

**Comment by luizbills** [comment]
Sublime text.

**Comment by joelnet** [comment]
Ahh okay. I used that before vscode. Are you using an eslint plugin? How is the integration?

**Comment by luizbills** [comment]
> Are you using an eslint plugin?

No. but I have already used

> How is the integration?
Just install a sublime text plugin, install eslint globally and configure binary paths if necessary. Works very well. Can format/lint with command or on save.

**Comment by joelnet** [comment]
Awesome. Sounds like a great editor. I haven't used it since I switched to vscode. So I don't know what the development on it has been.

**Comment by joelnet** [comment]
CLI already created. Any issues related to the CLI should go there.
