### ISSUE TITLE
Missing eslint rules

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#121]
- `no-if` - prevent `if` statements.
- `max-param-call` - similar to `max-param`, but limit arguments to calls to 1 param.

**Comment by luizbills** [comment]
I guess you should maintain your own eslint rules (`eslint-plugin-mojiscript`) to avoid unexpected changes in https://github.com/jfmengels/eslint-plugin-fp or others

**Comment by joelnet** [comment]
Documentation could be improved, but rules are being moved here: https://github.com/joelnet/eslint-config-mojiscript

**Comment by joelnet** [comment]
Issue moved to the `eslint-config-mojiscript` project https://github.com/joelnet/eslint-config-mojiscript/issues/1
