### ISSUE TITLE
sleep should be cancellable

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#147]
`sleep` should be cancellable. As it is written now, it cannot be used for throttling or debouncing.

**Comment by GrosSacASac** [comment]
sleep is defined here https://github.com/joelnet/MojiScript/blob/master/threading/sleep.js

We could use AbortController similar to fetch as a mechanism to enable cancellation
https://developer.mozilla.org/en-US/docs/Web/API/AbortController

I would like to take this issue

**Comment by GrosSacASac** [comment]
https://dom.spec.whatwg.org/#abortcontroller-api-integration

**Comment by joelnet** [comment]
This is a good idea. You may need to create a new `cancellableSleep` function to take in the additional argument.  Some ideas, move `sleep.js` to `sleep/index.js` and create `sleep/abortable.js`.

Hit me up here or on twitter if you need help with anything.

**Comment by joelnet** [comment]
This could be a good resource, since it's a TC39 proposal: https://github.com/tc39/proposal-cancellation

**Comment by GrosSacASac** [comment]
I think is has been abandoned...

**Comment by joelnet** [comment]
Hmmm... that's not great.

**Comment by joelnet** [comment]
I just created a Discord chat channel. Hit me up there if you have questions. https://discord.gg/Gg7ptD5

**Comment by GrosSacASac** [comment]
Links redirects to a page with infinite spinner ...

**Comment by joelnet** [comment]
The site must have been down. I just checked it and it's working now.

**Comment by GrosSacASac** [comment]
https://github.com/joelnet/MojiScript/pull/235

**Comment by GrosSacASac** [comment]
Only works in the browser, could you create a PR to add AbortController to Node too ?

**Comment by joelnet** [comment]
Ahh. It seems `AbortController` is a browser api. I can look into getting this to work on node.

Cheers!
