### ISSUE TITLE
Create a sort method

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#167]
Create `list/sort.js`

**Expected:**

```javascript
const ascending = a => b => a - b

sort (ascending) ([ 1, 2, 3 ])
```

**Should support `range`:**

```javascript
import range from 'mojiscript/list/range'

const ascending = a => b => a - b

sort (ascending) (range (0) (11))
```

**Acceptance Criteria:**

* Should have 100% code coverage
* Sorts arrays
* Sorts iterables
* Does not mutate original object.
* Throws an exception if item to sort is not supported.

**Comment by leniquenoralez** [comment]
I can take a shot at this.

**Comment by joelnet** [comment]
Awesome! Hit me up on Twitter if you have any questions!
