### ISSUE TITLE
create list/reduceWhile

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#169]
Copy `reduce` and Create `reduceWhile`.

`reduceWhile` will take 1 additional argument, a predicate to determine if the iteration should stop or continue.

The predicate will be `predicate :: Any -> Any -> Boolean`

**Example:**

```javascript
const reduce = require('mojiscript/list/reduce')
const reduceWhile = require('mojiscript/list/reduceWhile')
const range = require('mojiscript/list/range')

const add = a => b => a + b
const lte6 = acc => x => acc <= 6

reduce (add) (0) (range (0) (4)) //=> 6
reduce (lt7) (add) (0) (range (0) (Infinity)) //=> 6
```

**Acceptance Criteria:**

* reduceWhile is created.
* unit tests are created to support example use-cases.
* API.md documentation is updated to include the new function.

**Comment by DennyScott** [comment]
I can take this one on!

**Comment by joelnet** [comment]
Awesome @DennyScott . Hit me up here or on twitter if you have questions!
