### ISSUE TITLE
create list/head and list/tail

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#171]
Create two functions: list/head and list/tail.

**Expected Behavior:**

```javascript
import head from 'mojiscript/list/head'
import tail from 'mojiscript/list/tail'
import range from 'mojiscript/list/range'

head ([ 1, 2, 3 ]) //=> 1
head (range (1) (Infinity)) //=> 1
head (null) //=> Error('type {type} not supported')
head ({}) //=> Error('type {type} not supported')

tail ([ 1, 2, 3 ]) //=> [ 2, 3 ]
tail (range (1) (4)) //=> [ 2, 3 ]
tail (null) //=> Error('type {type} not supported')
tail ({}) //=> Error('type {type} not supported')
```

**Acceptance Criteria:**

* list/head and list/tail are created.
* unit tests are created to support example use-cases.
* API.md documentation is updated to include the new functions.

**Comment by joelnet** [comment]
Awesome. Hit me up on twitter or here if you have any questions!

**Comment by Corned** [comment]
How should the following piece of code work?
```js
import tail from 'mojiscript/list/tail'
import range from 'mojiscript/list/range'

tail (range (1) (Infinity))
```

We'll run into some obvious issues when trying to get the tail of that range.
