### ISSUE TITLE
create object/clone

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#177]
Create new function `clone`  to shallow clone objects.

* Create a new directory `clone`.
* Should be able to clone an Array. (use es6 spread operator)
* Should be able to clone an Object. (use spread operator)
* Should be able to clone a Function. (check this answer https://stackoverflow.com/a/6772648/504836)
* numbers and strings should just be returned.
* all other types should throw an exception.

Consider having a single export as `clone` and internal functions for each type of clone.

**Comment by mdowds** [comment]
I'll take a look at this

**Comment by Nilkamal** [comment]
I want to work on this ? Can i ?

**Comment by mdowds** [comment]
A question about this - should the implementation of this be in pure JS or can it use other parts of MS? I can see `is` and `cond` being useful for this.

**Comment by luizbills** [comment]
@mdowds you can to use internal and public functions.

**Comment by mdowds** [comment]
I've created a WIP PR as I've come across a small issue - eslint is giving me unexpected token on the object spread operator. Do any changes need to be made to the eslint config to support this?

**Comment by joelnet** [comment]
Update this section in the `.eslintrc.yml`

```yaml
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
```

Can you also move the `clone.js` into `object/clone.js`. I think we're going to add more features into the `object` category in the near future. 

Your code looks great btw. Thanks!

Can you add some tests for `null` and `undefined`? Those should just be passed through.

Also, we just added support for `Set` and `Map`. How to clone: https://stackoverflow.com/questions/30626070/shallow-clone-an-es6-map-or-set

Cheers!

**Comment by mdowds** [comment]
Thank you! I've made those changes.

**Comment by joelnet** [comment]
Great work!
