### ISSUE TITLE
Enhance type/is is to detect Map and Set

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#178]
Enhance `type/is` is to detect `Map` and `Set`

**Expected:**

```javascript
import is from 'mojiscript/type/is'

const map = new Map()
const set = new Set()

is (Map) (map) //=> true
is (Set) (set) //=> true
```

You can find some info on this here: https://stackoverflow.com/questions/35298314/check-if-a-javascript-object-is-map-or-set-ecmascript-2015

**Acceptance Criteria**

* Map detects Maps
* Set detects Sets
* Update documentation to include `Map` and `Set`.
* Include unit tests.

**Comment by henryjw** [comment]
Hey @joelnet I've added unit tests for `Map` and `Set` and it looks like the current code already supports them. Also, where should the documentation be updated? I don't see mention of `is()` anywhere in the README or in the examples.

**Comment by joelnet** [comment]
Oh I was just in that section (be sure to checkout the develop branch) https://github.com/joelnet/MojiScript/pull/195

I wouldn't be surprised if it already detects it. I just added so many cases. Some basic tests would be a good idea.

You can find the docs here: https://github.com/joelnet/MojiScript/blob/master/API.md#is

**Comment by henryjw** [comment]
Oh ok. I hadn't checked the API documentation.
