### ISSUE TITLE
Create a logo for MojiScript

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#179]
Create a logo similar to the unofficial JavaScript logo at https://github.com/voodootikigod/logo.js

Should use the same colors. If you have an opinion on colors, submit them along with the original colors.

Font should be open source, like Roboto or Open Sans.

Add to folder `media`. If you have an original PSD, include that as well.

Sizes to include: 1200 x 1200, 800 x 800, 400 x 400, 200 x 200, 64 x 64
Image type: PNG

**Comment by kk-o** [comment]
Finished with this, attached is a preview. Can I be given the appropriate permissions to create a new pull request? 
![ms_logo_200](https://user-images.githubusercontent.com/22601829/46986206-f0ead000-d0a2-11e8-981f-cb05809e67e5.png)

**Comment by luizbills** [comment]
Micro$oft?

**Comment by joelnet** [comment]
Looks good! 

You will have to fork the repo, then you will be able to submit a pull request from the forked repo.

**Comment by joelnet** [comment]
Logo is up!
