### ISSUE TITLE
imrpove eslint rules

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#181]
The eslint rules in the root are not useful. They are for setup for MojiScript, but MojiScript is written in JavaScript. It would make more sense to have a JavaScript ruleset.

My proposal is to change the root to extend the `airbnb` rules, with modifications to exclude semicolons and to use single quote. Also exclude the examples folder in `.eslintignore`.

Then every folder in examples needs to have an `.eslintrc.yml`  that extends the mojiscript rules.

**Comment by henryjw** [comment]
I'll take a stab at it.

**Comment by joelnet** [comment]
You might also have to remove all of the `/* eslint-disable */` lines.

**Comment by henryjw** [comment]
Submitted the PR. BTW, cool project!

**Comment by joelnet** [comment]
This one was a doozy! 131 files modified!

Great work man. This was no easy task!

I forgot what a pain the airbnb style is. Maybe I should have just gone eslint recommended.

I'm glad you are enjoying the project. I'd love to see anything you build with it!

**Comment by henryjw** [comment]
Yea. The AirBnB style guide is so particular, but it makes the code so clean!

For sure. I'll be sure to share any cool stuff I build with it!
