### ISSUE TITLE
Slow unit test execution

### ISSUE THREAD

**Issue by henryjw** [joelnet/MojiScript#209]
It takes up to a minute to run unit tests. It would be nice if they were faster. Could it be a Jest issue?

**Comment by joelnet** [comment]
That is odd. Here are my results:

`npm test`

```
Test Suites: 43 passed, 43 total
Tests:       216 passed, 216 total
Snapshots:   0 total
Time:        2.414s
Ran all test suites.
```

`npm run test:coverage`
```
Test Suites: 43 passed, 43 total
Tests:       216 passed, 216 total
Snapshots:   0 total
Time:        3.295s
Ran all test suites.
```

I do have a fast machine though. But 1 minute seems slow.

When you install your node modules, try doing an `npm ci` instead of an `npm install`. Maybe there's a difference in dependencies?

**Comment by henryjw** [comment]
Come to think of it, it might be that I'm running them in the Windows Linux Subsystem. I'll try running it on a Mac or Linux system to see if the performance is better there.

**Comment by henryjw** [comment]
Ran it on Mac and it only took 3s. Looks to be an issue with the Windows Linux Subsystem.
