### ISSUE TITLE
Refactor types into type/_allTypes.js

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#216]
Move `@@type` properties out of `Maybe`, `Just`, `Nothing`, and `type/is` and into a new file `type/_allTypes.js`.

`allTypes.js` should be imported into each type to get it's type. 

This way, the `toString()` nonsense in `type/is.js` can be replaced with a regular comparison.

**Comment by ksami** [comment]
I'll work on this

**Comment by joelnet** [comment]
Great job. Thanks for the contribution!
