### ISSUE TITLE
Improve Maybe functions

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#220]
* Rename `Maybe.toMaybe` to `Maybe.fromNull`.
* Create `Maybe.fromFalsy`
* Create tests

These should work in a similar way to Monet's Maybe type: https://github.com/monet/monet.js/blob/develop/docs/MAYBE.md

```javascript
Maybe.fromNull()
Maybe.fromNull(null)
Maybe.fromNull(undefined)
// => None

Maybe.fromFalsy()
Maybe.fromFalsy(null)
Maybe.fromFalsy(0)
Maybe.fromFalsy('')
Maybe.fromFalsy(false)
// => None
```

**Comment by johnpaulada** [comment]
Can I try working on this too? What test library do you use?

**Comment by joelnet** [comment]
Jest. You can see some example tests written here: https://github.com/joelnet/MojiScript/tree/master/type/__tests__

**Comment by joelnet** [comment]
I just created a Discord chat channel. Hit me up there if you have questions. https://discord.gg/Gg7ptD5

**Comment by joelnet** [comment]
How is your progress on this? Do you need any help?

I just created a Discord chat channel. Hit me up there if you have questions. https://discord.gg/Gg7ptD5
