### ISSUE TITLE
Add flatMap and leftMap to Maybe types

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#221]
Add the `flatMap` and `leftMap` functions to `Just` and `Nothing`.

* `Nothing.flatMap` will work just like `map` and return `Nothing`.
* `Just.flatMap` will be similar to `map`, but it will not box the value in a `Just`.
* `Just.leftMap` will not execute the function and return the `Just`.
* `Nothing.leftMap` will execute the function and return the value.

**Expected behavior**

```javascript
const upper = s => typeof s === 'string' ? Just (s.toUpperCase ()) : Nothing

Just ('abc').flatMap (upper) //=> Just('ABC')
Just (123).flatMap (upper) //=> Nothing
Nothing.flatMap (upper) //=> Nothing

Just ('abc').leftMap (upper) //=> Just('abc')
Nothing.leftMap (() => Just ('ABC')) //=> Just('ABC')
Nothing.leftMap (() => Nothing) //=> Nothing
```

**Comment by johnpaulada** [comment]
Hi! Can I try working on this?

**Comment by joelnet** [comment]
Sure!

**Comment by joelnet** [comment]
I just created a Discord chat channel. Hit me up there if you have questions. https://discord.gg/Gg7ptD5

**Comment by joelnet** [comment]
How is your progress going? Do you need any help?

I just created a Discord chat channel. Hit me up there if you have questions. https://discord.gg/Gg7ptD5

**Comment by thanhcng** [comment]
Hi, can I work on this issue instead?

**Comment by johnpaulada** [comment]
Sorry I was having internet difficulties. Third world country 😞
