### ISSUE TITLE
Create webpack example

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#222]
Create an example project in the `examples/webpack-hello-world` directory to demonstrate how to run `webpack` and `webpack-dev-server`.

Project will need to be setup for webpack.

A basic hello world output do a `div` in the DOM is good enough.

**Comment by edgarMejia** [comment]
Can I try working on this?

**Comment by joelnet** [comment]
Go for it!

**Comment by joelnet** [comment]
Use example code from https://github.com/joelnet/MojiScript/tree/master/examples/parcel-hello-world

**Comment by joelnet** [comment]
I just created a Discord chat channel. Hit me up there if you have questions. https://discord.gg/Gg7ptD5

**Comment by edgarMejia** [comment]
Perfect!

**Comment by joelnet** [comment]
How is your progress going? Do you need any help?

**Comment by joelnet** [comment]
Short answer is to copy this one  https://github.com/joelnet/MojiScript/tree/master/examples/parcel-hello-world but use `webpack` and `webpack-dev-server` instead of `parcel`.
