### ISSUE TITLE
Create a parcel example

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#223]
Create a basic hello world with `parcel` that outputs `Hello World` to a DIV in the DOM.

This project should be put in `examples/parcel-hello-world`

**Comment by edgarMejia** [comment]
With a readme?

**Comment by joelnet** [comment]
You can copy this example https://github.com/joelnet/MojiScript/tree/master/examples/hello-world or any other example in https://github.com/joelnet/MojiScript/tree/master/examples/
