### ISSUE TITLE
fix typo in docs (type/is)

### ISSUE THREAD

**Issue by joelnet** [joelnet/MojiScript#272]
There's a typo on the page https://mojiscript.js.org/#/type-is

```javascript
import is from 'mojiscript/types/is'
```

should read:

```javascript
import is from 'mojiscript/type/is'
```

**Comment by jatinkumarg** [comment]
Hey, can I fix it?

**Comment by joelnet** [comment]
Sure thing!

**Comment by joelnet** [comment]
Thanks for the contribution. Your changes have been merged into the master branch!
